name: Format Check

on:
  push:
    branches: ["master", "dev", "format"]
    paths:
      - '.github/workflows/format_check.yml'
      - '**.jl'
  pull_request:
    branches: ["master", "dev"]
    paths:
      - '.github/workflows/format_check.yml'
      - '**.jl'
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.x]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v1
      - name: Install JuliaFormatter and format
        run: |
          julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
          julia  -e 'using JuliaFormatter; format(".", verbose=true)'
      - uses: julia-actions/cache@v1
      - name: Format check
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end'
