name: Make Docs
on:
  workflow_dispatch:  # Manually trigger
  push:
    branches: master
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
    tags: '*'
  pull_request:
    branches: master
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
    
jobs:
  make_docs:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/make_docs.yml@master
    with:
      use_FuseRegistry: false